[build-system]
requires = ["scikit-build-core>=0.10"]
build-backend = "scikit_build_core.build"

[project]
name = "ctpx"
version = "6.7.2.6"
requires-python = "==3.12.*"
description = "CTP (China Futures Market) Python API Wrapper with multi-implementation support"
dependencies = []
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "csuduan", email = "csuduan@qq.com"},
]
keywords = ["ctp", "futures", "china", "trading", "api", "swig"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: C++",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Topic :: Office/Business :: Financial",
]
urls = {Homepage = "https://github.com/csuduan/pyctp", Repository = "https://github.com/csuduan/pyctp"}

[tool.scikit-build]
minimum-version = "0.10"
cmake.source-dir = "api"
wheel.packages = ["src/ctpx"]
install.strip = true


[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
default = true

[tool.cibuildwheel]
build = "cp312-*"
skip = "*-musllinux_*"
manylinux-x86_64-image = "manylinux_2_34"

[tool.cibuildwheel.linux]
before-build = """
dnf install -y cmake swig boost-devel patchelf
"""
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel}"
